DROP TABLE
IF EXISTS `home_user`;
-- 用户
CREATE TABLE `home_user` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` CHAR (20) NOT NULL,
	`password` VARCHAR (64) NOT NULL,
	`error_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `unique_index_user` (`username`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `home_file`;
-- 文件
CREATE TABLE `home_file` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED,
	`uuid` CHAR (32) NOT NULL,
	`name` VARCHAR (64),
	`type` VARCHAR (10),
  `level` TINYINT UNSIGNED NOT NULL DEFAULT 0,
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE KEY `unique_index_file` (`uuid`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `home_tag`;
-- 文件的标签
CREATE TABLE `home_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR (20),
  `user_id` BIGINT UNSIGNED,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index_file_tag` (`name`, `user_id`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE
IF EXISTS `home_file_tag`;
-- 文件与标签的关联关系
CREATE TABLE `home_file_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_id` BIGINT UNSIGNED NOT NULL,
  `file_id` BIGINT UNSIGNED NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index_file_tag` (`tag_id`, `file_id`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8;